# Generated by Django 4.2.29 on 2026-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('EXT', 'Extrudeuse'), ('IMP', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('COMP', 'Complexeuse'), ('DEC', 'Découpeuse'), ('DEC2', 'Découpeuse 2'), ('SAC_FC', 'Machine Fond Carré'), ('SAC_SO', 'Machine Soudure'), ('NETT_CL', 'Nettoyage Cliché'), ('NETT_AN', 'Nettoyage Anilox'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type'),
        ),
    ]
