# Generated by Django 4.2.29 on 2026-04-13 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_employee_telephone_alter_machine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_event', models.CharField(choices=[('OF', 'Ordre de Fabrication'), ('MAINTENANCE', 'Maintenance'), ('PREVENTIVE', 'Maintenance Préventive'), ('ARRET', 'Arrêt programmé'), ('NETTOYAGE', 'Nettoyage'), ('AUTRE', 'Autre')], default='OF', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(verbose_name='Date/heure début')),
                ('date_fin', models.DateTimeField(verbose_name='Date/heure fin')),
                ('toute_la_journee', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('couleur', models.CharField(choices=[('#3b82f6', 'Bleu'), ('#22c55e', 'Vert'), ('#f59e0b', 'Orange'), ('#ef4444', 'Rouge'), ('#8b5cf6', 'Violet'), ('#06b6d4', 'Cyan'), ('#ec4899', 'Rose'), ('#6b7280', 'Gris')], default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_events', to='core.machine', verbose_name='Machine')),
                ('of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_events', to='core.ordrefabrication', verbose_name='OF lié')),
                ('om', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_events', to='core.ordremaintenance', verbose_name='OM lié')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_events', to='core.employee', verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Événement planning',
                'verbose_name_plural': 'Événements planning',
                'ordering': ['date_debut'],
            },
        ),
    ]
