# Generated by Django 4.2.29 on 2026-04-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planningevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanningEvent',
        ),
    ]
