# Generated by Django 4.2.29 on 2026-09-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_delete_planningevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculTempsProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_job', models.CharField(max_length=200, verbose_name='Nom du Job / Commande')),
                ('type_produit', models.CharField(choices=[('ETIQUETTE', 'Étiquette (avec Pas & Poses)'), ('FILM_MONO', 'Film Mono-couche'), ('COMPLEXE', 'Film Complexe / Duplex / Triplex'), ('AUTRE', 'Autre produit sur bobine')], default='ETIQUETTE', max_length=20, verbose_name='Type de Produit')),
                ('quantite_commandee', models.FloatField(default=1000000, verbose_name='Quantité Commandée')),
                ('unite_quantite', models.CharField(choices=[('UNITE', "Nombre d'Étiquettes / Pièces"), ('METRE', 'Mètres Linéaires (ML)'), ('KG', 'Kilogrammes (KG)')], default='UNITE', max_length=10, verbose_name='Unité Commandée')),
                ('pas_mm', models.FloatField(default=275.0, verbose_name='Pas de coupe / Avance (mm)')),
                ('laize_produit_mm', models.FloatField(default=65.0, verbose_name='Laize Produit / Étiquette (mm)')),
                ('grammage_g_m2', models.FloatField(default=80.0, verbose_name='Grammage / Masse surfacique (g/m²)')),
                ('laize_bobine_mere_mm', models.FloatField(default=825.0, verbose_name='Laize Bobine Mère (mm)')),
                ('longueur_bobine_mere_m', models.FloatField(default=10000.0, verbose_name='Longueur Bobine Mère (m)')),
                ('process_impression', models.CharField(choices=[('FLEXO', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('SANS', 'Sans Impression (Découpe seule)')], default='FLEXO', max_length=10, verbose_name='Process Impression')),
                ('vitesse_impression_mmin', models.FloatField(default=200.0, verbose_name='Vitesse Impression (m/min ou tr/min)')),
                ('temps_calage_impression_min', models.IntegerField(default=45, verbose_name='Temps Calage Impression (min)')),
                ('temps_decalage_bobine_min', models.IntegerField(default=10, verbose_name='Changement/Décalage par Bobine Mère (min)')),
                ('vitesse_decoupe_mmin', models.FloatField(default=250.0, verbose_name='Vitesse Découpe (m/min ou tr/min)')),
                ('temps_calage_decoupe_min', models.IntegerField(default=20, verbose_name='Temps Calage Découpe (min)')),
                ('temps_rebobinage_fille_min', models.IntegerField(default=3, verbose_name='Temps Évacuation/Rebobinage par Bobine Fille (min)')),
                ('date_debut_prevue', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Heure de Démarrage')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('machine_decoupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculs_decoupe', to='core.machine', verbose_name='Machine Découpe')),
                ('machine_impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculs_impression', to='core.machine', verbose_name='Machine Impression')),
            ],
            options={
                'verbose_name': 'Calcul Prévisionnel de Temps',
                'verbose_name_plural': 'Calculs Prévisionnels de Temps',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
