# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consommationencre_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('produit', models.CharField(max_length=200, verbose_name='Produit')),
                ('support', models.CharField(max_length=100, verbose_name='Support')),
                ('quantite_lancee', models.FloatField(default=0, verbose_name='Quantité Lancée (kg)')),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='Lot')),
                ('laize', models.FloatField(default=0, verbose_name='Laize (mm)')),
                ('equipe', models.CharField(choices=[('A', 'Équipe A'), ('B', 'Équipe B'), ('C', 'Équipe C')], default='A', max_length=5, verbose_name='Équipe')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure Début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure Fin')),
                ('prod_ml', models.FloatField(default=0, verbose_name='Prod ML')),
                ('dechets_demarrage', models.FloatField(default=0, verbose_name='Déchets Démarrage (kg)')),
                ('dechets_lisiere', models.FloatField(default=0, verbose_name='Déchets Lisière (kg)')),
                ('dechets_jonction', models.FloatField(default=0, verbose_name='Déchets Jonction (kg)')),
                ('dechets_transport', models.FloatField(default=0, verbose_name='Déchets Transport (kg)')),
                ('prod_kg', models.FloatField(default=0, verbose_name='Prod KG')),
                ('rebobinage_kg', models.FloatField(default=0, verbose_name='Rebobinage KG')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine')),
            ],
            options={
                'verbose_name': 'Saisie Production',
                'verbose_name_plural': 'Saisies Production',
                'ordering': ['-date', '-heure_debut'],
            },
        ),
    ]
