# Generated by Django 4.2.29 on 2026-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calcultempsproduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelier',
            options={'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Pointage', 'verbose_name_plural': 'Pointages'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Salon de chat', 'verbose_name_plural': 'Salons de chat'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'verbose_name': 'Compétence employé', 'verbose_name_plural': 'Compétences employés'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': 'Demande de congé', 'verbose_name_plural': 'Demandes de congés'},
        ),
        migrations.AlterModelOptions(
            name='medicalvisit',
            options={'verbose_name': 'Visite médicale', 'verbose_name_plural': 'Visites médicales'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'Bulletin de paie', 'verbose_name_plural': 'Bulletins de paie'},
        ),
        migrations.AlterModelOptions(
            name='protectiveequipment',
            options={'verbose_name': 'EPI', 'verbose_name_plural': 'EPI'},
        ),
        migrations.AlterModelOptions(
            name='salarygrid',
            options={'verbose_name': 'Grille salariale', 'verbose_name_plural': 'Grilles salariales'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Affectation shift', 'verbose_name_plural': 'Affectations shifts'},
        ),
        migrations.AlterModelOptions(
            name='workincident',
            options={'verbose_name': 'Incident de travail', 'verbose_name_plural': 'Incidents de travail'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Planning de travail', 'verbose_name_plural': 'Plannings de travail'},
        ),
        migrations.AddField(
            model_name='productionentry',
            name='laize_bobine_mere_mm',
            field=models.FloatField(blank=True, default=825.0, null=True, verbose_name='Laize Bobine Mère (mm)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='laize_produit_mm',
            field=models.FloatField(blank=True, default=65.0, null=True, verbose_name='Laize Étiquette / Produit (mm)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='longueur_bobine_mere_m',
            field=models.FloatField(blank=True, default=10000.0, null=True, verbose_name='Longueur Bobine Mère (m)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='pas_mm',
            field=models.FloatField(blank=True, default=275.0, null=True, verbose_name='Pas de coupe / Avance (mm)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='quantite_commandee_unites',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantité Étiquettes / Pièces Commandées'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='temps_calage_min',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Temps de Calage (min)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='type_process',
            field=models.CharField(choices=[('FLEXO', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('DECOUPE', 'Découpeuse / Refendeuse'), ('AUTRE', 'Autre Processus')], default='FLEXO', max_length=20, verbose_name='Type Processus'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='vitesse_machine_trmin',
            field=models.FloatField(blank=True, default=200.0, null=True, verbose_name='Vitesse Machine (tr/min ou m/min)'),
        ),
    ]
