# Generated by Django 4.2.29 on 2026-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_atelier_options_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'verbose_name': 'Document employé', 'verbose_name_plural': 'Documents employés'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Poste', 'verbose_name_plural': 'Postes'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Équipe (Shift)', 'verbose_name_plural': 'Équipes (Shifts)'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='machineauthorization',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('EXT', 'Extrudeuse'), ('IMP', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('COMP', 'Complexeuse'), ('DEC', 'Grande Découpe (DCM Panther 1350)'), ('DEC2', 'Petite Découpe (DCM Panther 1)'), ('SAC_FC', 'Machine Fond Carré'), ('SAC_SO', 'Machine Soudure'), ('NETT_CL', 'Nettoyage Cliché'), ('NETT_AN', 'Nettoyage Anilox'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='type_process',
            field=models.CharField(choices=[('FLEXO', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('DECOUPE', 'Grande Découpe (DCM Panther 1350)'), ('DECOUPE2', 'Petite Découpe (DCM Panther 1)'), ('AUTRE', 'Autre Processus')], default='FLEXO', max_length=20, verbose_name='Type Processus'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
