# Generated by Django 4.2.29 on 2026-03-31 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_productionentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='interactionlog',
            options={'ordering': ['-date'], 'verbose_name': "Journal d'interaction", 'verbose_name_plural': "Journaux d'interaction"},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-date', '-version'], 'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='client',
            name='ca_estime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='CA Estimé (DA)'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code Client Interne'),
        ),
        migrations.AddField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Commercial responsable'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée"),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, choices=[('NORD', 'Nord'), ('SUD', 'Sud'), ('EST', 'Est'), ('OUEST', 'Ouest'), ('CENTRE', 'Centre'), ('EXPORT', 'Export')], max_length=10, verbose_name='Région / Zone'),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('FLEXO', 'Flexographie'), ('HELIO', 'Héliogravure'), ('EXTRUSION', 'Extrusion'), ('AUTRE', 'Autre')], default='FLEXO', max_length=20, verbose_name="Segment d'activité"),
        ),
        migrations.AddField(
            model_name='client',
            name='size',
            field=models.CharField(blank=True, choices=[('TPE', 'TPE (< 10 salariés)'), ('PME', 'PME (10-250)'), ('ETI', 'ETI (250-5000)'), ('GE', 'Grande Entreprise (> 5000)')], max_length=10, verbose_name='Taille du client'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email direct'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone direct'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='role_custom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fonction personnalisée'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Commercial'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientcontact', verbose_name='Contact concerné'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='next_action',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prochaine action'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='next_action_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prochaine action'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commande_creee',
            field=models.BooleanField(default=False, verbose_name='Commande créée'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Commercial'),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_validite',
            field=models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au"),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Contact Principal'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom Prénom'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='role',
            field=models.CharField(choices=[('ACHAT', 'Directeur Achat'), ('TECH', 'Responsable Technique'), ('COMM', 'Commercial'), ('LOGI', 'Responsable Logistique'), ('DIR', 'Directeur Général'), ('COMPTA', 'Comptabilité'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date / Heure'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='details',
            field=models.TextField(blank=True, verbose_name='Détails complets'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Objet / Résumé'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='type',
            field=models.CharField(choices=[('CALL', 'Appel téléphonique'), ('EMAIL', 'Email'), ('MEET', 'Rendez-vous'), ('NOTE', 'Note interne'), ('VISITE', 'Visite client')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('EXPIRED', 'Expiré'), ('SIGNED', 'Signé')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant Total (DA)'),
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'opportunité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('QUALIFICATION', 'Qualification'), ('PROPOSITION', 'Proposition envoyée'), ('NEGOCIATION', 'Négociation'), ('GAGNE', 'Gagné ✓'), ('PERDU', 'Perdu ✗')], default='PROSPECT', max_length=20, verbose_name='Étape')),
                ('valeur_estimee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur Estimée (DA)')),
                ('probabilite', models.IntegerField(default=20, verbose_name='Probabilité de gain (%)')),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ouverture")),
                ('date_cloture_prevue', models.DateField(blank=True, null=True, verbose_name='Date de clôture prévue')),
                ('date_cloture_reelle', models.DateField(blank=True, null=True, verbose_name='Date de clôture réelle')),
                ('motif_perte', models.CharField(blank=True, max_length=200, verbose_name='Motif de perte')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Commercial responsable')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='opportunite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opportunite', verbose_name='Opportunité liée'),
        ),
        migrations.AddField(
            model_name='quote',
            name='opportunite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opportunite', verbose_name='Opportunité liée'),
        ),
    ]
