# Generated by Django 4.2.29 on 2026-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
