# Generated by Django 4.2.29 on 2026-04-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_client_options_alter_interactionlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence BC')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé fournisseur'), ('CONFIRME', 'Confirmé'), ('RECU_PARTIEL', 'Reçu partiellement'), ('RECU_TOTAL', 'Reçu totalement'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateField(default=django.utils.timezone.now, verbose_name='Date commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('date_livraison_reelle', models.DateField(blank=True, null=True, verbose_name='Livraison réelle')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total (DA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Conditions')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'emplacement")),
                ('type', models.CharField(choices=[('GENERAL', 'Magasin Général'), ('TAMPON', 'Stock Tampon'), ('PRODUCTION', 'Zone Production'), ('DECHET', 'Zone Déchets'), ('QUARANTAINE', 'Quarantaine')], default='GENERAL', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Emplacement Stock',
                'verbose_name_plural': 'Emplacements Stock',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100, verbose_name='N° Lot fournisseur')),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date réception')),
                ('quantite_initiale', models.FloatField(default=0, verbose_name='Quantité initiale (kg)')),
                ('quantite_restante', models.FloatField(default=0, verbose_name='Quantité restante (kg)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (DA/kg)')),
                ('statut', models.CharField(choices=[('CONFORME', 'Conforme ✓'), ('BLOQUE', 'Bloqué ✗'), ('EN_ATTENTE', 'En attente contrôle'), ('QUARANTAINE', 'Quarantaine')], default='EN_ATTENTE', max_length=20, verbose_name='Statut qualité')),
                ('certificat_qualite', models.FileField(blank=True, null=True, upload_to='certificats/', verbose_name='Certificat qualité (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stocklocation', verbose_name='Emplacement')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='Fournisseur')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.material', verbose_name='Matière première')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'verbose_name_plural': 'Lots de stock',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='ca_estime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume Estimé (KG/Étiquette)'),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='valeur_estimee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Volume Estimé (KG/Étiquette)'),
        ),
        migrations.CreateModel(
            name='StockSeuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommation_journaliere_moy', models.FloatField(default=0, verbose_name='Conso. moyenne/jour (kg)')),
                ('delai_fournisseur_jours', models.IntegerField(default=7, verbose_name='Délai fournisseur (jours)')),
                ('stock_securite_jours', models.IntegerField(default=3, verbose_name='Jours de sécurité supplémentaires')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seuil_intelligent', to='core.material', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Seuil intelligent',
                'verbose_name_plural': 'Seuils intelligents',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée (Achat / Réception)'), ('SORTIE', 'Sortie (Production)'), ('TRANSFERT', 'Transfert interne'), ('AJUSTEMENT', 'Ajustement inventaire'), ('RETOUR', 'Retour fournisseur'), ('PERTE', 'Perte / Déchet')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.FloatField(verbose_name='Quantité (kg)')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif / Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('emplacement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entree', to='core.stocklocation', verbose_name='Emplacement destination')),
                ('emplacement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortie', to='core.stocklocation', verbose_name='Emplacement source')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='core.stocklot', verbose_name='Lot')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine', verbose_name='Machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.material', verbose_name='Matière')),
                ('of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productionorder', verbose_name='OF lié')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.FloatField(verbose_name='Quantité commandée (kg)')),
                ('quantite_recue', models.FloatField(default=0, verbose_name='Quantité reçue (kg)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (DA/kg)')),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.boncommande')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Ligne BC',
            },
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence DA')),
                ('quantite_demandee', models.FloatField(verbose_name='Quantité demandée (kg)')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la demande')),
                ('urgence', models.CharField(choices=[('NORMALE', 'Normale'), ('URGENTE', 'Urgente'), ('CRITIQUE', 'Critique !!')], default='NORMALE', max_length=10, verbose_name="Niveau d'urgence")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise pour validation'), ('VALIDEE', 'Validée ✓'), ('REFUSEE', 'Refusée ✗'), ('COMMANDEE', 'Bon de commande émis')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date création')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date validation')),
                ('date_besoin', models.DateField(blank=True, null=True, verbose_name='Date besoin souhaitée')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boncommande', verbose_name='BC généré')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Matière demandée')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_achat', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
    ]
