# Generated by Django 4.2.29 on 2026-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='grammage_g_m2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Grammage / Masse surfacique (g/m²)'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='unite_commande',
            field=models.CharField(choices=[('UNITE', 'Pièces / Étiquettes / Sacs'), ('KG', 'Tonnage (KG / Tonnes)'), ('ML', 'Mètres Linéaires (ML)')], default='UNITE', max_length=10, verbose_name='Unité de Commande'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='quantite_commandee_unites',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantité Commandée'),
        ),
    ]
