# Generated by Django 4.2.29 on 2026-04-02 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_boncommande_stocklocation_stocklot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1, verbose_name='N° étape')),
                ('input_quantity', models.FloatField(default=0, help_text='Quantité à traiter pour cette étape', verbose_name='Qté entrée (kg)')),
                ('output_quantity', models.FloatField(default=0, help_text='Quantité réellement produite', verbose_name='Qté sortie (kg)')),
                ('waste_quantity', models.FloatField(default=0, verbose_name='Déchets (kg)')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Début prévu')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin prévue')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PLANNED', 'Planifié'), ('READY', 'Prêt'), ('IN_PROGRESS', 'En cours'), ('PAUSED', 'En pause'), ('COMPLETED', 'Complété'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Notes techniques')),
                ('qc_passed', models.BooleanField(blank=True, null=True, verbose_name='QC validée')),
                ('qc_date', models.DateTimeField(blank=True, null=True, verbose_name='Date QC')),
                ('qc_notes', models.TextField(blank=True, verbose_name='Observations QC')),
                ('order_in_of', models.IntegerField(default=1, help_text='1 = première étape, 2 = deuxième, etc.', verbose_name="Ordre dans l'OF")),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine', verbose_name='Machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Étape de fabrication',
                'verbose_name_plural': 'Étapes de fabrication',
                'ordering': ['production_order', 'order_in_of'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du processus')),
                ('process_type', models.CharField(choices=[('EXTRUSION', 'Extrusion (Film)'), ('FLEXO', 'Impression Flexographie'), ('HELIO', 'Impression Héliogravure'), ('COMPLEXAGE', 'Complexage / Laminage'), ('DECOUPE', 'Découpe / Façonnage'), ('EMBALLAGE', 'Emballage'), ('AUTRE', 'Autre processus')], max_length=20, verbose_name='Type de processus')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('estimated_duration_minutes', models.IntegerField(default=60, verbose_name='Durée estimée (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Processus de production',
                'verbose_name_plural': 'Processus de production',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SemiFinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('quantity', models.FloatField(verbose_name='Quantité (kg)')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('CREATED', 'Créé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Complété'), ('REJECTED', 'Rejeté'), ('REWORK', 'À retravailler')], default='CREATED', max_length=20, verbose_name='Statut qualité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conformity_checked', models.BooleanField(default=False, verbose_name='Conforme QC')),
                ('conformity_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stocklocation', verbose_name='Emplacement')),
                ('of_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_finished_products', to='core.productionorderstep', verbose_name='Étape OF')),
            ],
            options={
                'verbose_name': 'Produit semi-fini',
                'verbose_name_plural': 'Produits semi-finis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStepMachineSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(blank=True, help_text='Ex: 150 m/min', max_length=100, verbose_name='Vitesse')),
                ('pressure', models.CharField(blank=True, help_text='Ex: 2.5 bar', max_length=100, verbose_name='Pression')),
                ('temperature', models.CharField(blank=True, help_text='Ex: 180°C', max_length=100, verbose_name='Température')),
                ('mandrel_diameter', models.FloatField(blank=True, null=True, verbose_name='Diamètre mandrin (mm)')),
                ('spool_diameter', models.FloatField(blank=True, null=True, verbose_name='Diamètre bobine fille (mm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de setup')),
                ('setup_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de configuration')),
                ('setup_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_setups', to=settings.AUTH_USER_MODEL, verbose_name='Configuré par')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_setup', to='core.productionorderstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Configuration machine',
                'verbose_name_plural': 'Configurations machine',
            },
        ),
        migrations.CreateModel(
            name='ProductionStepHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Créée'), ('STARTED', 'Démarrée'), ('PAUSED', 'Mise en pause'), ('RESUMED', 'Reprise'), ('COMPLETED', 'Complétée'), ('QC_PASSED', 'QC Validée'), ('QC_FAILED', 'QC Échouée'), ('REJECTED', 'Rejetée'), ('MACHINE_CHANGE', 'Machine changée'), ('OPERATOR_CHANGE', 'Opérateur changé'), ('PARAMETER_CHANGE', 'Paramètres modifiés')], max_length=20, verbose_name="Type d'événement")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Ancienne valeur')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Nouvelle valeur')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='core.productionorderstep', verbose_name='Étape')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique étape',
                'verbose_name_plural': 'Historiques étapes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, help_text='A, B, C, Nuit, etc.', max_length=50, verbose_name='Équipe / Poste')),
                ('start_date', models.DateTimeField(verbose_name='Début')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('quantity_planned', models.FloatField(verbose_name='Quantité planifiée (kg)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine', verbose_name='Machine')),
                ('of_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.productionorderstep', verbose_name='Étape OF')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur prévu')),
            ],
            options={
                'verbose_name': 'Planification',
                'verbose_name_plural': 'Planifications',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='productionorderstep',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productionprocess', verbose_name='Processus'),
        ),
        migrations.AddField(
            model_name='productionorderstep',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.productionorder', verbose_name='Ordre de fabrication'),
        ),
        migrations.AddField(
            model_name='productionorderstep',
            name='qc_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_steps', to=settings.AUTH_USER_MODEL, verbose_name='Inspecteur QC'),
        ),
        migrations.AddField(
            model_name='productionorderstep',
            name='tooling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tooling', verbose_name='Outillage utilisé'),
        ),
        migrations.CreateModel(
            name='ProductionOrderImproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_number', models.CharField(max_length=50, unique=True, verbose_name='N° OF')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='N° de lot')),
                ('total_quantity_planned', models.FloatField(default=0, verbose_name='Quantité totale prévue (kg)')),
                ('mandrel_diameter_mm', models.FloatField(blank=True, null=True, verbose_name='Diamètre mandrin (mm)')),
                ('spool_diameter_mm', models.FloatField(blank=True, null=True, verbose_name='Diamètre bobine fille (mm)')),
                ('planned_start_date', models.DateField(verbose_name='Date de lancement prévue')),
                ('planned_end_date', models.DateField(verbose_name='Date de fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Date de lancement réelle')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('LAUNCHED', 'Lancé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('bat_file', models.FileField(blank=True, null=True, upload_to='bat/', verbose_name='BAT Validé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('opportunite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opportunite', verbose_name='Opportunité liée')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicalproduct', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Ordre de fabrication (amélioré)',
                'verbose_name_plural': 'Ordres de fabrication (améliorés)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionorderstep',
            unique_together={('production_order', 'order_in_of')},
        ),
    ]
