# Generated by Django 4.2.29 on 2026-04-02 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_productionorderstep_productionprocess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.FloatField(default=0, verbose_name='Quantité prévue')),
                ('quantite_reelle', models.FloatField(default=0, verbose_name='Quantité réelle')),
                ('date_consommation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Consommation matière',
                'verbose_name_plural': 'Consommations matières',
            },
        ),
        migrations.CreateModel(
            name='EtapeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etape', models.IntegerField(default=1, verbose_name='N° Étape')),
                ('nom_etape', models.CharField(blank=True, max_length=100, verbose_name='Nom étape')),
                ('quantite_entree', models.FloatField(default=0, verbose_name='Quantité entrée (kg)')),
                ('quantite_sortie', models.FloatField(default=0, verbose_name='Quantité sortie (kg)')),
                ('quantite_rebut', models.FloatField(default=0, verbose_name='Rebuts (kg)')),
                ('date_prevue_debut', models.DateTimeField(blank=True, null=True, verbose_name='Début prévu')),
                ('date_prevue_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin prévue')),
                ('date_debut_reel', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('date_fin_reel', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('temps_arret_minutes', models.IntegerField(default=0, verbose_name="Temps d'arrêt (min)")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PRET', 'Prêt à lancer'), ('EN_COURS', 'En cours'), ('PAUSE', 'En pause'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('genere_semi_produit', models.BooleanField(default=True, verbose_name='Génère semi-produit')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Instructions')),
            ],
            options={
                'verbose_name': 'Étape de production',
                'verbose_name_plural': 'Étapes de production',
                'ordering': ['of', 'numero_etape'],
            },
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_of', models.CharField(max_length=50, unique=True, verbose_name='N° OF')),
                ('numero_lot', models.CharField(blank=True, max_length=100, verbose_name='N° Lot')),
                ('quantite_prevue', models.FloatField(default=0, verbose_name='Quantité prévue (kg)')),
                ('quantite_produite', models.FloatField(default=0, verbose_name='Quantité produite (kg)')),
                ('quantite_conforme', models.FloatField(default=0, verbose_name='Quantité conforme (kg)')),
                ('quantite_rebut', models.FloatField(default=0, verbose_name='Rebuts (kg)')),
                ('dimension_mandrin', models.FloatField(blank=True, default=76, null=True, verbose_name='Dimension mandrin (mm)')),
                ('diametre_bobine_fille', models.FloatField(blank=True, default=0, null=True, verbose_name='Diamètre bobine fille (mm)')),
                ('laize', models.FloatField(blank=True, default=0, null=True, verbose_name='Laize (mm)')),
                ('epaisseur', models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur (μm)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_lancement', models.DateField(blank=True, null=True, verbose_name='Date lancement')),
                ('date_prevue_fin', models.DateField(blank=True, null=True, verbose_name='Date prévue fin')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date fin réelle')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('LANCE', 'Lancé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('bat_file', models.FileField(blank=True, null=True, upload_to='bat/', verbose_name='BAT Validé')),
                ('fiche_technique', models.FileField(blank=True, null=True, upload_to='fiches_techniques/', verbose_name='Fiche technique')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Instructions')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_fabrication', to='core.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('opportunite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opportunite', verbose_name='Opportunité liée')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_fabrication', to='core.technicalproduct', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Ordre de Fabrication',
                'verbose_name_plural': 'Ordres de Fabrication',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du processus')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre_defaut', models.IntegerField(default=0, verbose_name='Ordre par défaut')),
                ('icone', models.CharField(default='⚙️', max_length=10, verbose_name='Icône (emoji)')),
                ('couleur', models.CharField(default='#6c757d', max_length=7, verbose_name='Couleur (hex)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de processus',
                'verbose_name_plural': 'Types de processus',
                'ordering': ['ordre_defaut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SemiProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('type_semi_produit', models.CharField(choices=[('FILM_EXTRUDE', 'Film extrudé'), ('FILM_IMPRIME', 'Film imprimé'), ('FILM_COMPLEXE', 'Film complexé'), ('BOBINE_MERE', 'Bobine mère'), ('BOBINE_FILLE', 'Bobine fille'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type')),
                ('quantite', models.FloatField(default=0, verbose_name='Quantité (kg)')),
                ('unite', models.CharField(default='kg', max_length=10, verbose_name='Unité')),
                ('laize', models.FloatField(blank=True, default=0, null=True, verbose_name='Laize (mm)')),
                ('longueur', models.FloatField(blank=True, default=0, null=True, verbose_name='Longueur (m)')),
                ('poids_bobine', models.FloatField(blank=True, default=0, null=True, verbose_name='Poids bobine (kg)')),
                ('numero_bobine', models.CharField(blank=True, max_length=50, verbose_name='N° Bobine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date péremption')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('CONSOMME', 'Consommé'), ('BLOQUE', 'Bloqué qualité'), ('REBUT', 'Rebut')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('conforme', models.BooleanField(default=True, verbose_name='Conforme')),
                ('notes_qualite', models.TextField(blank=True, verbose_name='Notes qualité')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stocklocation', verbose_name='Emplacement')),
                ('etape_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_produits_consommes', to='core.etapeproduction', verbose_name='Étape de consommation')),
                ('etape_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_produits_generes', to='core.etapeproduction', verbose_name="Étape d'origine")),
                ('of_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_produits_generes', to='core.ordrefabrication', verbose_name="OF d'origine")),
            ],
            options={
                'verbose_name': 'Semi-produit',
                'verbose_name_plural': 'Semi-produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure')),
                ('type_evenement', models.CharField(choices=[('DEMARRAGE', 'Démarrage'), ('ARRET', 'Arrêt'), ('REPRISE', 'Reprise'), ('FIN', 'Fin'), ('PAUSE', 'Pause'), ('INCIDENT', 'Incident'), ('CONTROLE', 'Contrôle qualité'), ('CHANGEMENT', 'Changement série'), ('REGLAGE', 'Réglage')], max_length=20, verbose_name='Type')),
                ('cause_arret', models.CharField(blank=True, choices=[('PANNE', 'Panne machine'), ('REGLAGE', 'Réglage'), ('PAUSE', 'Pause opérateur'), ('MATIERE', 'Attente matière'), ('QUALITE', 'Problème qualité'), ('MAINTENANCE', 'Maintenance préventive'), ('CHANGEMENT', 'Changement de série'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Cause arrêt')),
                ('quantite_produite', models.FloatField(default=0, verbose_name='Quantité produite (kg)')),
                ('quantite_rebut', models.FloatField(default=0, verbose_name='Rebut (kg)')),
                ('vitesse_machine', models.FloatField(blank=True, default=0, null=True, verbose_name='Vitesse machine (m/min)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.etapeproduction', verbose_name='Étape')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Suivi de production',
                'verbose_name_plural': 'Suivis de production',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionorderstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='process',
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='qc_inspector',
        ),
        migrations.RemoveField(
            model_name='productionorderstep',
            name='tooling',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='of_step',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productionstephistory',
            name='step',
        ),
        migrations.RemoveField(
            model_name='productionstephistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productionstepmachinesetup',
            name='setup_by',
        ),
        migrations.RemoveField(
            model_name='productionstepmachinesetup',
            name='step',
        ),
        migrations.RemoveField(
            model_name='semifinishedproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='semifinishedproduct',
            name='location',
        ),
        migrations.RemoveField(
            model_name='semifinishedproduct',
            name='of_step',
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'verbose_name': 'Ordre de fabrication (ancien)', 'verbose_name_plural': 'Ordres de fabrication (anciens)'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('EXT', 'Extrudeuse'), ('IMP', 'Imprimeuse'), ('DEC', 'Découpeuse'), ('COMP', 'Complexeuse'), ('REF', 'Refendeuse')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductionOrderImproved',
        ),
        migrations.DeleteModel(
            name='ProductionOrderStep',
        ),
        migrations.DeleteModel(
            name='ProductionProcess',
        ),
        migrations.DeleteModel(
            name='ProductionSchedule',
        ),
        migrations.DeleteModel(
            name='ProductionStepHistory',
        ),
        migrations.DeleteModel(
            name='ProductionStepMachineSetup',
        ),
        migrations.DeleteModel(
            name='SemiFinishedProduct',
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='core.ordrefabrication', verbose_name='Ordre de Fabrication'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='process_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.processtype', verbose_name='Type de processus'),
        ),
        migrations.AddField(
            model_name='consommationmatiere',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='core.etapeproduction', verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='consommationmatiere',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stocklot', verbose_name='Lot'),
        ),
        migrations.AddField(
            model_name='consommationmatiere',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Matière première'),
        ),
        migrations.AlterUniqueTogether(
            name='etapeproduction',
            unique_together={('of', 'numero_etape')},
        ),
    ]
