# Generated by Django 4.2.29 on 2026-09-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productionentry_grammage_g_m2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelier',
            options={'ordering': ['ordre_affichage', 'nom'], 'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_planifiees', to='core.atelier', verbose_name='Atelier'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='developpement',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Développement (mm)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='nb_bobines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de bobines'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='numero_lot_etape',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Lot étape (ex: 90PE440-8)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation (RELIQUAT, BAT+PROD...)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='quantite_ml',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantité ML (mètres linéaires)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='support',
            field=models.CharField(blank=True, max_length=200, verbose_name='Support (ex: OPP 20 TRS 920MM)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation (Excel style)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='support',
            field=models.CharField(blank=True, max_length=100, verbose_name='Support global (ex: OPP 20 TRS)'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='atelier_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_types', to='core.atelier', verbose_name='Atelier associé'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='etape_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_production', to='core.etapeproduction', verbose_name='Étape liée'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='of_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_production', to='core.ordrefabrication', verbose_name='OF lié'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='numero_of',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° OF'),
        ),
        migrations.AlterField(
            model_name='semiproduit',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Référence'),
        ),
    ]
