# Generated by Django 4.2.29 on 2026-04-02 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_consommationmatiere_etapeproduction_ordrefabrication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du salon')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('GENERAL', 'Général'), ('PRODUCTION', 'Production'), ('COMMERCIAL', 'Commercial'), ('TECHNIQUE', 'Technique'), ('URGENCE', 'Urgences')], default='GENERAL', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='💬', max_length=10, verbose_name='Icône')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('membres', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Salon de chat',
                'verbose_name_plural': 'Salons de chat',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='En ligne')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chatroom', verbose_name='Salon actuel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Présence utilisateur',
                'verbose_name_plural': 'Présences utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('type_message', models.CharField(choices=[('TEXT', 'Texte'), ('SYSTEM', 'Système'), ('ALERT', 'Alerte'), ('FILE', 'Fichier')], default='TEXT', max_length=10, verbose_name='Type')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Fichier joint')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('lu_par', models.ManyToManyField(blank=True, related_name='messages_lus', to=settings.AUTH_USER_MODEL, verbose_name='Lu par')),
                ('of_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ordrefabrication', verbose_name='OF lié')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
