# Generated by Django 4.2.29 on 2026-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ficheproductionjournaliere_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichecomplexagederouleur1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichecomplexagederouleur2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichecomplexageenrouleur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichedecoupebobinefille',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichedecoupebobinemere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficheextrusionarret',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficheextrusionmatiere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichefondcarreequipe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficheimpressionbobineentree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficheimpressionbobineimprimee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficheimpressionencregroupe',
            options={'ordering': ['groupe_numero']},
        ),
        migrations.AlterField(
            model_name='ficheproductionjournaliere',
            name='type_fiche',
            field=models.CharField(choices=[('EXTRUSION', "Fiche Fabrication Journalière d'Extrusion"), ('FLEXO', 'Fiche Impression Journalière FLEXO'), ('HELIO', 'Fiche Impression Journalière HÉLIO'), ('COMPLEXAGE', 'Fiche Journalière Complexage (Duplex/Triplex)'), ('FONDS_CARRES', 'Fiche Fabrication Fonds Carrés'), ('DECOUPE', 'Fiche Journalière Découpe 1'), ('DECOUPE2', 'Fiche Journalière Découpe 2')], default='FLEXO', max_length=20, verbose_name='Type de Fiche'),
        ),
    ]
