# Generated by Django 4.2.29 on 2026-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fichecomplexagederouleur1_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheproductionjournaliere',
            name='numero_lot',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='N° Lot (Traçabilité ERP)'),
        ),
        migrations.AlterField(
            model_name='ficheproductionjournaliere',
            name='numero_doc',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='N° Doc / Lot de commande'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='numero_lot',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='N° Lot'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='lot',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Lot'),
        ),
    ]
