# Generated by Django 4.2.29 on 2026-09-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ficheproductionjournaliere_numero_lot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calcultempsproduction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planmaintenancepreventive',
            options={'verbose_name': 'Plan maintenance préventive', 'verbose_name_plural': 'Plans maintenance préventive'},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='of',
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('EXT', 'Extrudeuse'), ('IMP', 'Imprimeuse Flexo'), ('HELIO', 'Imprimeuse Hélio'), ('COMP', 'Complexeuse'), ('DEC', 'Grande Découpe'), ('DEC2', 'Petite Découpe'), ('SAC_FC', 'Machine Fond Carré'), ('SAC_SO', 'Machine Soudure'), ('NETT_CL', 'Nettoyage Cliché'), ('NETT_AN', 'Nettoyage Anilox'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='etape_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_production_anciennes', to='core.etapeproduction', verbose_name='Étape liée'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='of_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_production_anciennes', to='core.ordrefabrication', verbose_name='OF lié'),
        ),
    ]
