# Generated by Django 4.2.29 on 2026-09-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_calcultempsproduction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='core.ordrefabrication', verbose_name='OF lié'),
        ),
    ]
