# Generated by Django 4.2.29 on 2026-09-17 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_stockmovement_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence commande')),
                ('date_commande', models.DateField(default=django.utils.timezone.now, verbose_name='Date commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('date_livraison_reelle', models.DateField(blank=True, null=True, verbose_name='Date livraison réelle')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('EN_PRODUCTION', 'En production'), ('PRETE', 'Prête à livrer'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='État')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('conditions_paiement', models.CharField(blank=True, max_length=20, verbose_name='Conditions de paiement')),
                ('delai_livraison_jours', models.IntegerField(default=15, verbose_name='Délai livraison (jours)')),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT (DA)')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total (DA)')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Instructions')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Commande Client',
                'verbose_name_plural': 'Commandes Clients',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='conditions_paiement',
            field=models.CharField(blank=True, choices=[('COMPTANT', 'Comptant'), ('30J', '30 jours'), ('45J', '45 jours'), ('60J', '60 jours'), ('90J', '90 jours'), ('30J_FM', '30 jours fin de mois'), ('ACOMPTE_30', 'Acompte 30% + solde'), ('ACOMPTE_50', 'Acompte 50% + solde'), ('AUTRE', 'Autre')], default='', max_length=20, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_conversion',
            field=models.DateField(blank=True, null=True, verbose_name='Date conversion prospect → client'),
        ),
        migrations.AddField(
            model_name='client',
            name='delai_livraison_jours',
            field=models.IntegerField(default=15, verbose_name='Délai de livraison standard (jours)'),
        ),
        migrations.AddField(
            model_name='client',
            name='ice_nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='ICE / NIF / RC'),
        ),
        migrations.AddField(
            model_name='client',
            name='limite_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Limite de crédit (DA)'),
        ),
        migrations.AddField(
            model_name='client',
            name='remise_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise par défaut (%)'),
        ),
        migrations.AddField(
            model_name='client',
            name='source_prospect',
            field=models.CharField(blank=True, choices=[('SITE_WEB', 'Site web'), ('SALON', 'Salon / Foire'), ('RESEAU', 'Réseau / Recommandation'), ('APPEL_ENTRANT', 'Appel entrant'), ('PROSPECTION', 'Prospection active'), ('EMAILING', 'Emailing'), ('RESEAUX_SOCIAUX', 'Réseaux sociaux'), ('PARTENAIRE', 'Partenaire'), ('AUTRE', 'Autre')], default='', max_length=20, verbose_name='Source du prospect'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='date_prevue_commande',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue de commande'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='devis_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_liees', to='core.quote', verbose_name='Devis associé'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='material_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to='core.material', verbose_name='Matière principale requise'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='prix_estime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix estimé (DA)'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='produit_demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to='core.technicalproduct', verbose_name='Produit demandé'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='quantite_estimee',
            field=models.FloatField(default=0, verbose_name='Quantité estimée (kg)'),
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantite', models.FloatField(default=0, verbose_name='Quantité')),
                ('unite', models.CharField(default='kg', max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DA)')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise ligne (%)')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date livraison ligne')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commandeclient', verbose_name='Commande')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='core.material', verbose_name='Matière première liée')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='core.technicalproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne commande client',
                'verbose_name_plural': 'Lignes commandes clients',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DemandePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence DP')),
                ('objet', models.CharField(max_length=300, verbose_name='Objet de la demande')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('quantite_demandee', models.FloatField(default=0, verbose_name='Quantité demandée (kg)')),
                ('budget_indicatif', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Budget indicatif (DA)')),
                ('date_demande', models.DateField(default=django.utils.timezone.now, verbose_name='Date demande')),
                ('date_reponse_souhaitee', models.DateField(blank=True, null=True, verbose_name='Réponse souhaitée avant')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_ETUDE', 'En étude'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée')], default='NOUVELLE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_prix', to='core.client', verbose_name='Client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prix', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientcontact', verbose_name='Contact')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prix_creees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prix_origine', to='core.quote', verbose_name='Devis généré')),
                ('opportunite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prix', to='core.opportunite', verbose_name='Opportunité')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technicalproduct', verbose_name='Produit concerné')),
            ],
            options={
                'verbose_name': 'Demande de prix',
                'verbose_name_plural': 'Demandes de prix',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='core.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to=settings.AUTH_USER_MODEL, verbose_name='Commercial'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='core.quote', verbose_name="Devis d'origine"),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='of_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='core.ordrefabrication', verbose_name='OF lié'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='opportunite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.opportunite', verbose_name='Opportunité liée'),
        ),
    ]
