# Generated by Django 4.2.29 on 2026-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_commandeclient_client_conditions_paiement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapeproduction',
            options={'ordering': ['of', 'numero_etape'], 'verbose_name': 'Étape de production / Planification', 'verbose_name_plural': 'Étapes de production / Planifications'},
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='date_planifiee',
            field=models.DateField(blank=True, null=True, verbose_name='Date planifiée'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='equipe',
            field=models.CharField(blank=True, choices=[('A', 'Équipe A'), ('B', 'Équipe B'), ('C', 'Équipe C')], max_length=10, verbose_name='Équipe assignée'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='heure_debut_planifiee',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure début estimée'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='heure_fin_planifiee',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin estimée'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='ordre_passage',
            field=models.IntegerField(default=1, verbose_name='Ordre de passage sur machine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='shift',
            field=models.CharField(blank=True, choices=[('MATIN', 'Matin (06h-14h)'), ('SOIR', 'Soir (14h-22h)'), ('NUIT', 'Nuit (22h-06h)')], max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='date_prevue_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début prévu (Legacy)'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='date_prevue_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin prévue (Legacy)'),
        ),
    ]
