# Generated by Django 4.2.29 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_etapeproduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapeproduction',
            name='shift',
            field=models.CharField(blank=True, choices=[('MATIN', 'Matin (08h-16h)'), ('SOIR', 'Soir (16h-00h)'), ('NUIT', 'Nuit (00h-08h)')], max_length=10, verbose_name='Shift'),
        ),
    ]
