# Generated by Django 4.2.29 on 2026-09-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_etapeproduction_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDecoupeControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laize_mere_avant', models.CharField(blank=True, max_length=50, verbose_name='Laize Mère (Avant)')),
                ('laize_fille_apres', models.CharField(blank=True, max_length=50, verbose_name='Laize Fille (Après)')),
                ('impression_avant', models.CharField(blank=True, max_length=50, verbose_name='Impression (Avant)')),
                ('impression_apres', models.CharField(blank=True, max_length=50, verbose_name='Impression (Après)')),
                ('etat_bobine_avant', models.CharField(blank=True, max_length=50, verbose_name='État Bobine (Avant)')),
                ('etat_bobine_apres', models.CharField(blank=True, max_length=50, verbose_name='État Bobine (Après)')),
                ('froissage_avant', models.CharField(blank=True, max_length=50, verbose_name='Froissage (Avant)')),
                ('froissage_apres', models.CharField(blank=True, max_length=50, verbose_name='Froissage (Après)')),
                ('alignement_mandrin_avant', models.CharField(blank=True, max_length=50, verbose_name='Alignement Mandrin (Avant)')),
                ('alignement_mandrin_apres', models.CharField(blank=True, max_length=50, verbose_name='Alignement Mandrin (Après)')),
                ('nbr_jonction_avant', models.CharField(blank=True, max_length=50, verbose_name='Nbr Jonction (Avant)')),
                ('decalage_impress_avant', models.CharField(blank=True, max_length=50, verbose_name='Décalage Impression (Avant)')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_decoupe', to='core.ficheproductionjournaliere')),
            ],
            options={
                'verbose_name': 'Autocontrôle Découpe',
                'verbose_name_plural': 'Autocontrôles Découpe',
            },
        ),
        migrations.CreateModel(
            name='FicheDecoupeArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=150, verbose_name='Arrêt')),
                ('temps_min', models.IntegerField(default=0, verbose_name='Temps (min)')),
                ('dechets_kg', models.FloatField(default=0, verbose_name='Déchets (Kg)')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_decoupe', to='core.ficheproductionjournaliere')),
            ],
            options={
                'verbose_name': 'Arrêt Découpe',
                'verbose_name_plural': 'Arrêts Découpe',
            },
        ),
    ]
