# Generated by Django 4.2.29 on 2026-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fichedecoupecontrole_fichedecoupearret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='role',
            field=models.CharField(choices=[('ACHAT', "Attaché d'achat / Acheteur"), ('APPRO', 'Responsable Approvisionnement'), ('COMM', 'Commercial / Ventes'), ('TECH', 'Responsable Technique / Qualité'), ('LOGI', 'Responsable Logistique / Transport'), ('DIR', 'Directeur Général / Gérant'), ('COMPTA', 'Comptabilité / Finance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, verbose_name='Fonction'),
        ),
    ]
