# Generated by Django 4.2.29 on 2026-09-20 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_alter_clientcontact_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_dashboard', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('can_access_planning', models.BooleanField(default=False, verbose_name='Planning Gantt')),
                ('can_access_reporting', models.BooleanField(default=False, verbose_name='Reporting')),
                ('can_access_crm', models.BooleanField(default=False, verbose_name='CRM & Devis')),
                ('can_access_prepress', models.BooleanField(default=False, verbose_name='Prépresse & Outils')),
                ('can_access_planification', models.BooleanField(default=False, verbose_name='Planification Atelier')),
                ('can_access_production', models.BooleanField(default=False, verbose_name='Production Spécial')),
                ('can_access_stock', models.BooleanField(default=False, verbose_name='Stocks & Achats')),
                ('can_access_maintenance', models.BooleanField(default=False, verbose_name='Maintenance')),
                ('can_access_drh', models.BooleanField(default=False, verbose_name='Ressources Humaines')),
                ('can_access_chat', models.BooleanField(default=True, verbose_name="Chat d'Équipe")),
                ('can_access_import', models.BooleanField(default=False, verbose_name='Import Excel')),
                ('can_access_admin', models.BooleanField(default=False, verbose_name='Administration')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Module Utilisateur',
                'verbose_name_plural': 'Permissions Modules Utilisateurs',
            },
        ),
    ]
