# Generated by Django 4.2.29 on 2026-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usermodulepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('PRODUCTION', 'Production'), ('COMMERCIAL', 'Commercial'), ('TECHNIQUE', 'Technique'), ('URGENCE', 'Urgences'), ('DIRECT', 'Message Direct')], default='GENERAL', max_length=20, verbose_name='Type'),
        ),
    ]
