# Generated by Django 4.2.29 on 2026-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_chatroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeproduction',
            name='unite_sortie',
            field=models.CharField(choices=[('KG', 'KG'), ('ML', 'ML'), ('NB_ETIQUETTES', 'NB étiquettes'), ('NB_SACS', 'NB sacs')], default='ML', max_length=20, verbose_name='Unité de sortie'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='developpement',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Développement global (mm)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='diametre_bobine_fille_unite',
            field=models.CharField(choices=[('MM', 'Ø (mm)'), ('KG', 'Kg')], default='MM', max_length=10, verbose_name='Unité Ø bobine fille'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='quantite_ml',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantité sortie valeur'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='diametre_bobine_fille',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diamètre bobine fille'),
        ),
    ]
