# Generated by Django 4.2.29 on 2026-09-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_etapeproduction_unite_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrefabrication',
            name='placement_spot',
            field=models.CharField(blank=True, choices=[('1', 'En bas à gauche'), ('2', 'En bas au centre'), ('3', 'En bas à droite'), ('4', 'En haut à droite')], max_length=2, null=True, verbose_name='Placement spot'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='sens_defilement',
            field=models.CharField(blank=True, choices=[('1', 'Sens 1 (Tête en avant)'), ('2', 'Sens 2 (Pied en avant)'), ('3', 'Sens 3 (Droite en avant)'), ('4', 'Sens 4 (Gauche en avant)')], max_length=2, null=True, verbose_name='Sens de défilement'),
        ),
    ]
