# Generated by Django 4.2.29 on 2026-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ordrefabrication_placement_spot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_ep1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur 1'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_ep2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur 2'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_ep3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur 3'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_laize1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize 1'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_laize2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize 2'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_laize3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize 3'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_mp1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support1'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_mp2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support2'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='comp_mp3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support3'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_diametre_ext',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ø EXT Bobine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_jonctions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de jonction/bob'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_mandrin_int',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ø INT Mandrin (Dec)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_poids_moyen',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Poids Moyen Bobine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_qte_bobines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qté Bobines Fille'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='dec_type_mandrin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type Mandrin'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='fc_type_paquet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de paquet'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='imp_epaisseur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='imp_laize',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize Bobine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='imp_mandrin',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ø INT Mandrin'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='imp_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Support d'impression"),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='diametre_bobine_fille',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bobine fille (Valeur)'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='diametre_bobine_fille_unite',
            field=models.CharField(choices=[('MM', 'Ø (mm)'), ('KG', 'Kg')], default='MM', max_length=10, verbose_name='Unité Bobine fille'),
        ),
    ]
