# Generated by Django 4.2.29 on 2026-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_etapeproduction_comp_ep1_etapeproduction_comp_ep2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeproduction',
            name='ext_epaisseur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur Extrusion'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='ext_laize',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize Extrusion'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='ext_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Support Extrusion'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='comp_mp1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support1 (Contre collage)'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='comp_mp2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support2 (Triplex)'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='comp_mp3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qté MP support3 (Quadriplex)'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='imp_epaisseur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Épaisseur du support'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='numero_lot_etape',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Lot étape'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='support',
            field=models.CharField(blank=True, max_length=200, verbose_name='Support global'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='diametre_bobine_fille_unite',
            field=models.CharField(choices=[('MM', 'mm'), ('KG', 'Kg')], default='MM', max_length=10, verbose_name='Unité Bobine fille'),
        ),
    ]
