# Generated by Django 4.2.29 on 2026-09-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_etapeproduction_ext_epaisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Code Produit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
    ]
