# Generated by Django 4.2.29 on 2026-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_material_code_alter_material_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='initial_quantity',
            field=models.FloatField(default=0, verbose_name='Stock Initial (au départ)'),
        ),
    ]
