# Generated by Django 4.2.29 on 2026-09-30 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_material_initial_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Matière première', 'verbose_name_plural': 'Matières premières'},
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='laize',
            field=models.IntegerField(blank=True, null=True, verbose_name='Laize / Width (mm)'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='longueur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longueur / Length (m)'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=200, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom Complet')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste / Rôle')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Direct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Contact Fournisseur',
                'verbose_name_plural': 'Contacts Fournisseurs',
            },
        ),
    ]
