# Generated by Django 4.2.29 on 2026-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_material_options_material_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommandeclient',
            name='developpement_fabrication',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Développement (mm)'),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='laize_fabrication',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize (mm)'),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='poses_fabrication',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Nombre poses'),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='structure_json',
            field=models.TextField(blank=True, help_text='Sauvegarde silencieuse du calcul', null=True, verbose_name='Structure Technique JSON'),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='type_calcul',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('POIDS', 'Bobines (Poids)'), ('PIECES', 'Sacs/Étiquettes (Pièces)')], default='STANDARD', max_length=20, verbose_name='Type Calcul'),
        ),
        migrations.AddField(
            model_name='material',
            name='densite_iso',
            field=models.FloatField(default=1.0, help_text='OPP=0.91, PET=1.39, PE=0.92, ALU=2.70, PAPIER=1.0', verbose_name='Densité (g/cm³) ISO'),
        ),
        migrations.AddField(
            model_name='material',
            name='micronage_standard',
            field=models.IntegerField(blank=True, help_text='Ex: 20, 30, 38...', null=True, verbose_name='Micronage (µm)'),
        ),
    ]
