# Generated by Django 4.2.29 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_lignecommandeclient_developpement_fabrication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='grammage',
            field=models.FloatField(blank=True, help_text='Ex: 70, 80, 90 g/m² (Papiers/Cartons)', null=True, verbose_name='Grammage (g/m²)'),
        ),
        migrations.AddField(
            model_name='material',
            name='metrage_standard',
            field=models.FloatField(blank=True, help_text='Métrage standard de la bobine en mètres', null=True, verbose_name='Métrage / Longueur (m)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='micronage_standard',
            field=models.IntegerField(blank=True, help_text='Ex: 12, 15, 20, 30, 40...', null=True, verbose_name='Micronage (µm)'),
        ),
    ]
