# Generated by Django 4.2.29 on 2026-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_material_grammage_material_metrage_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='sous_categorie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sous-catégorie (Auto)'),
        ),
    ]
