# Generated by Django 4.2.29 on 2026-10-08 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_material_sous_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproduct',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='developpement_mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Développement (mm)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='graveur',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Graveur'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='impression',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='laize_gravure_mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Laize Gravure (mm)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='nb_poses_laize',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Nombre de poses (Laize)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='nb_poses_pas',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Nombre de poses (Pas)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='ref_graveur',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Référence Graveur'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='sens_bobine',
            field=models.CharField(blank=True, choices=[('1', 'Sens 1'), ('2', 'Sens 2'), ('3', 'Sens 3'), ('4', 'Sens 4'), ('5', 'Sens 5'), ('6', 'Sens 6'), ('7', 'Sens 7'), ('8', 'Sens 8')], max_length=2, null=True, verbose_name="Sens d'enroulement"),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='spot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spot (mm x mm)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='support_impression',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Support d'impression"),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='tech_sheet_file',
            field=models.FileField(blank=True, null=True, upload_to='tech_sheets/', verbose_name='Fiche Technique Originale (PDF/Image)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='type_dossier',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau Dossier'), ('REGRAVURE_SIMPLE', 'Regravure Simple'), ('REGRAVURE_MODIF', 'Regravure Avec Modification')], default='NOUVEAU', max_length=50, verbose_name='Type de dossier'),
        ),
        migrations.CreateModel(
            name='PrepressColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=1, verbose_name='N°')),
                ('nom_couleur', models.CharField(max_length=100, verbose_name='Couleurs (Ex: CYAN, MAGENTA...)')),
                ('anilox', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anilox')),
                ('adhesif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adhésif')),
                ('viscosite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viscosité')),
                ('type_encre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Type Encre')),
                ('formule_encre', models.CharField(blank=True, max_length=250, null=True, verbose_name='Formule Encre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couleurs_flexo', to='core.technicalproduct')),
            ],
            options={
                'verbose_name': 'Couleur Fiche Technique',
                'verbose_name_plural': 'Couleurs Fiche Technique',
                'ordering': ['ordre'],
            },
        ),
    ]
