# Generated by Django 4.2.29 on 2026-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_technicalproduct_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproduct',
            name='spot_placement',
            field=models.CharField(blank=True, choices=[('1', 'Bas Gauche'), ('2', 'Bas Centre'), ('3', 'Bas Droite'), ('4', 'Haut Droite')], max_length=2, null=True, verbose_name='Placement Spot'),
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='artwork_file',
            field=models.FileField(blank=True, upload_to='artwork/', verbose_name='Fichier Graphique / Fiche (AI/PDF)'),
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='tech_sheet_file',
            field=models.FileField(blank=True, null=True, upload_to='tech_sheets/', verbose_name='Fiche Technique Originale (PDF)'),
        ),
    ]
