# Generated by Django 4.2.29 on 2026-10-08 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_technicalproduct_spot_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooling',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='tooling',
            name='metrage_realise',
            field=models.FloatField(default=0, verbose_name='Métrage cumulé (ML)'),
        ),
        migrations.AddField(
            model_name='tooling',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='tooling',
            name='current_impressions',
            field=models.IntegerField(default=0, verbose_name='Nombre de Tours (Calcul auto)'),
        ),
        migrations.AlterField(
            model_name='tooling',
            name='max_impressions',
            field=models.IntegerField(default=1000000, verbose_name='Durée de vie théorique (tours)'),
        ),
        migrations.AlterField(
            model_name='tooling',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Code (Cliché/Cylindre)'),
        ),
    ]
