# Generated by Django 4.2.29 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_tooling_date_creation_tooling_metrage_realise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproduct',
            name='bat_status',
            field=models.CharField(choices=[('ATTENTE', '⏳ En attente de BAT'), ('VALIDE', '✅ BAT Validé (Prêt)'), ('REFUSE', '❌ Suspendu / Obsolète')], default='ATTENTE', max_length=20, verbose_name='Statut BAT'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='is_obsolete',
            field=models.BooleanField(default=False, verbose_name='Fiche Obsolète (Archivée)'),
        ),
        migrations.AddField(
            model_name='technicalproduct',
            name='version',
            field=models.CharField(default='V1.0', max_length=20, verbose_name='Version'),
        ),
    ]
