# Generated by Django 4.2.29 on 2026-10-08 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_technicalproduct_bat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='structure_json',
            field=models.TextField(blank=True, null=True, verbose_name='Structure Technique JSON'),
        ),
        migrations.CreateModel(
            name='ClientProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix Unitaire (DA)')),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme (kg)'), ('piece', 'Pièce / Étiquette'), ('ml', 'Mètre Linéaire (ml)'), ('forfait', 'Forfait global')], default='kg', max_length=20, verbose_name='Unité')),
                ('remise_specifique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise spécifique (%)')),
                ('date_application', models.DateField(default=django.utils.timezone.now, verbose_name='Applicable depuis')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_specifiques', to='core.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_commerciaux', to='core.technicalproduct')),
            ],
            options={
                'verbose_name': 'Tarif Client / Produit',
                'verbose_name_plural': 'Tarifs Clients / Produits',
                'unique_together': {('client', 'product')},
            },
        ),
    ]
