# Generated by Django 4.2.29 on 2026-10-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_lignecommandeclient_structure_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproduct',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_techniques', to='core.client', verbose_name='Client'),
        ),
    ]
