# Generated by Django 4.2.29 on 2026-10-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_technicalproduct_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproduct',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_techniques', related_query_name='technicalproduct', to='core.client', verbose_name='Client'),
        ),
    ]
